# Generated by Django 3.2 on 2021-04-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0002_auto_20210408_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(blank=True, choices=[('', 'Выберите валюту'), ('Wona', 'WON'), ('USDollars', 'USD'), ('UzSum', 'UZS')], default='', max_length=20, verbose_name='Валюта'),
        ),
    ]
