# Generated by Django 3.2 on 2021-04-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0007_alter_carshop_img_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='condition',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='carshop',
            name='description_car',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='carshop',
            name='img_car',
            field=models.ImageField(default='default.png', null=True, upload_to='cars/', verbose_name='Картинка'),
        ),
    ]
